export const gameOutcomeMultiplier = {
  DICE: 10001,
  HILO: 52,
  CARDS: 104,
};

// total game outcomes expected in each request
export const totalOutcomes = {
  DICE: 1,
  HILO: 104,
  CARDS: 104,
};

// cards mapping with their respective order
export const cards = [
  'AH',
  'AD',
  'AC',
  'AS',
  '2H',
  '2D',
  '2C',
  '2S',
  '3H',
  '3D',
  '3C',
  '3S',
  '4H',
  '4D',
  '4C',
  '4S',
  '5H',
  '5D',
  '5C',
  '5S',
  '6H',
  '6D',
  '6C',
  '6S',
  '7H',
  '7D',
  '7C',
  '7S',
  '8H',
  '8D',
  '8C',
  '8S',
  '9H',
  '9D',
  '9C',
  '9S',
  '10H',
  '10D',
  '10C',
  '10S',
  'JH',
  'JD',
  'JC',
  'JS',
  'QH',
  'QD',
  'QC',
  'QS',
  'KH',
  'KD',
  'KC',
  'KS',
];

// map images to the constants receiving from the API (2H, 2S, 2D, 2C)
export const cardImageMapping = {
  '2H': require('../public/images/2_of_hearts.png'),
  '2D': require('../public/images/2_of_diamonds.png'),
  '2C': require('../public/images/2_of_clubs.png'),
  '2S': require('../public/images/2_of_spades.png'),
  '3H': require('../public/images/3_of_hearts.png'),
  '3D': require('../public/images/3_of_diamonds.png'),
  '3C': require('../public/images/3_of_clubs.png'),
  '3S': require('../public/images/3_of_spades.png'),
  '4H': require('../public/images/4_of_hearts.png'),
  '4D': require('../public/images/4_of_diamonds.png'),
  '4C': require('../public/images/4_of_clubs.png'),
  '4S': require('../public/images/4_of_spades.png'),
  '5H': require('../public/images/5_of_hearts.png'),
  '5D': require('../public/images/5_of_diamonds.png'),
  '5C': require('../public/images/5_of_clubs.png'),
  '5S': require('../public/images/5_of_spades.png'),
  '6H': require('../public/images/6_of_hearts.png'),
  '6D': require('../public/images/6_of_diamonds.png'),
  '6C': require('../public/images/6_of_clubs.png'),
  '6S': require('../public/images/6_of_spades.png'),
  '7H': require('../public/images/7_of_hearts.png'),
  '7D': require('../public/images/7_of_diamonds.png'),
  '7C': require('../public/images/7_of_clubs.png'),
  '7S': require('../public/images/7_of_spades.png'),
  '8H': require('../public/images/8_of_hearts.png'),
  '8D': require('../public/images/8_of_diamonds.png'),
  '8C': require('../public/images/8_of_clubs.png'),
  '8S': require('../public/images/8_of_spades.png'),
  '9H': require('../public/images/9_of_hearts.png'),
  '9D': require('../public/images/9_of_diamonds.png'),
  '9C': require('../public/images/9_of_clubs.png'),
  '9S': require('../public/images/9_of_spades.png'),
  '10H': require('../public/images/10_of_hearts.png'),
  '10D': require('../public/images/10_of_diamonds.png'),
  '10C': require('../public/images/10_of_clubs.png'),
  '10S': require('../public/images/10_of_spades.png'),
  'JH': require('../public/images/jack_of_hearts.png'),
  'JD': require('../public/images/jack_of_diamonds.png'),
  'JC': require('../public/images/jack_of_clubs.png'),
  'JS': require('../public/images/jack_of_spades.png'),
  'QH': require('../public/images/queen_of_hearts.png'),
  'QD': require('../public/images/queen_of_diamonds.png'),
  'QC': require('../public/images/queen_of_clubs.png'),
  'QS': require('../public/images/queen_of_spades.png'),
  'KH': require('../public/images/king_of_hearts.png'),
  'KD': require('../public/images/king_of_diamonds.png'),
  'KC': require('../public/images/king_of_clubs.png'),
  'KS': require('../public/images/king_of_spades.png'),
  'AH': require('../public/images/ace_of_hearts.png'),
  'AD': require('../public/images/ace_of_diamonds.png'),
  'AC': require('../public/images/ace_of_clubs.png'),
  'AS': require('../public/images/ace_of_spades.png')
};
export default {cardImageMapping, cards, totalOutcomes, gameOutcomeMultiplier}